In [28]:
def describe(x):
    print("Type: ", x.type())
    print("Shape: ", x.shape)
    print("Value: ", x)
    return x

In [5]:
import torch

print(describe(torch.Tensor(2,3)))

Type:  <class 'torch.Tensor'>
Shape:  torch.Size([2, 3])
Value:  tensor([[9.1837e-39, 8.4490e-39, 1.0102e-38],
        [1.0561e-38, 1.0010e-38, 9.2756e-39]])
(<class 'torch.Tensor'>, torch.Size([2, 3]), tensor([[9.1837e-39, 8.4490e-39, 1.0102e-38],
        [1.0561e-38, 1.0010e-38, 9.2756e-39]]))


In [6]:
device = torch.device('cuda' if torch.cuda.is_available else 'gpu')

In [24]:
try:
    describe(device)
except:
    pass

Type:  <class 'torch.device'>


In [8]:
describe(torch.rand(2, 3)) 
describe(torch.randn(2,3)) # normalised

Type:  <class 'torch.Tensor'>
Shape:  torch.Size([2, 3])
Value:  tensor([[0.3953, 0.8311, 0.9215],
        [0.1242, 0.3636, 0.9194]])
Type:  <class 'torch.Tensor'>
Shape:  torch.Size([2, 3])
Value:  tensor([[-0.1247, -0.1133,  0.6944],
        [ 0.2207, -0.3254,  1.0822]])


(torch.Tensor,
 torch.Size([2, 3]),
 tensor([[-0.1247, -0.1133,  0.6944],
         [ 0.2207, -0.3254,  1.0822]]))

In [9]:
describe(torch.zeros(2,3))

Type:  <class 'torch.Tensor'>
Shape:  torch.Size([2, 3])
Value:  tensor([[0., 0., 0.],
        [0., 0., 0.]])


(torch.Tensor,
 torch.Size([2, 3]),
 tensor([[0., 0., 0.],
         [0., 0., 0.]]))

In [10]:
describe(torch.ones(2,3))

Type:  <class 'torch.Tensor'>
Shape:  torch.Size([2, 3])
Value:  tensor([[1., 1., 1.],
        [1., 1., 1.]])


(torch.Tensor,
 torch.Size([2, 3]),
 tensor([[1., 1., 1.],
         [1., 1., 1.]]))

In [13]:
x = torch.ones(2,3)
describe(x)

describe(x.fill_(5))

Type:  <class 'torch.Tensor'>
Shape:  torch.Size([2, 3])
Value:  tensor([[1., 1., 1.],
        [1., 1., 1.]])
Type:  <class 'torch.Tensor'>
Shape:  torch.Size([2, 3])
Value:  tensor([[5., 5., 5.],
        [5., 5., 5.]])


tensor([[5., 5., 5.],
        [5., 5., 5.]])

In [16]:
x = torch.Tensor([[1,2,3], [4,5,6]])

describe(x)

Type:  <class 'torch.Tensor'>
Shape:  torch.Size([2, 3])
Value:  tensor([[1., 2., 3.],
        [4., 5., 6.]])


tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [21]:
import numpy as np

x = np.random.rand(2,3)

describe(x)

x = np.random.randn(2,3)

describe(x)

Type:  <class 'numpy.ndarray'>
Shape:  (2, 3)
Value:  [[0.29928039 0.13125998 0.34292078]
 [0.40052394 0.12556718 0.25874984]]
Type:  <class 'numpy.ndarray'>
Shape:  (2, 3)
Value:  [[-1.54155841 -0.4455095   1.15503083]
 [ 0.96122963 -0.45365868 -1.94354082]]


array([[-1.54155841, -0.4455095 ,  1.15503083],
       [ 0.96122963, -0.45365868, -1.94354082]])

In [22]:
x = torch.from_numpy(x)

describe(x)

Type:  <class 'torch.Tensor'>
Shape:  torch.Size([2, 3])
Value:  tensor([[-1.5416, -0.4455,  1.1550],
        [ 0.9612, -0.4537, -1.9435]], dtype=torch.float64)


tensor([[-1.5416, -0.4455,  1.1550],
        [ 0.9612, -0.4537, -1.9435]], dtype=torch.float64)

In [25]:
x = x.long()

describe(x)

Type:  <class 'torch.Tensor'>
Shape:  torch.Size([2, 3])
Value:  tensor([[-1,  0,  1],
        [ 0,  0, -1]])


tensor([[-1,  0,  1],
        [ 0,  0, -1]])

In [29]:
x = torch.FloatTensor(torch.randn(2,3))

describe(x)

Type:  torch.FloatTensor
Shape:  torch.Size([2, 3])
Value:  tensor([[-0.2889,  1.8275, -0.3408],
        [-0.3970,  0.3792,  0.3986]])


tensor([[-0.2889,  1.8275, -0.3408],
        [-0.3970,  0.3792,  0.3986]])

Now lets look at some of the tensor operations.

In [30]:
torch.add(x,x)

describe(x)

Type:  torch.FloatTensor
Shape:  torch.Size([2, 3])
Value:  tensor([[-0.2889,  1.8275, -0.3408],
        [-0.3970,  0.3792,  0.3986]])


tensor([[-0.2889,  1.8275, -0.3408],
        [-0.3970,  0.3792,  0.3986]])

In [38]:
x = torch.arange(18)

describe(x)

x = x.view(2,3,3)

describe(x)

Type:  torch.LongTensor
Shape:  torch.Size([18])
Value:  tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17])
Type:  torch.LongTensor
Shape:  torch.Size([2, 3, 3])
Value:  tensor([[[ 0,  1,  2],
         [ 3,  4,  5],
         [ 6,  7,  8]],

        [[ 9, 10, 11],
         [12, 13, 14],
         [15, 16, 17]]])


tensor([[[ 0,  1,  2],
         [ 3,  4,  5],
         [ 6,  7,  8]],

        [[ 9, 10, 11],
         [12, 13, 14],
         [15, 16, 17]]])

In [39]:
describe(torch.sum(x, dim=0))

Type:  torch.LongTensor
Shape:  torch.Size([3, 3])
Value:  tensor([[ 9, 11, 13],
        [15, 17, 19],
        [21, 23, 25]])


tensor([[ 9, 11, 13],
        [15, 17, 19],
        [21, 23, 25]])

In [40]:
describe(torch.sum(x, dim=-1))

Type:  torch.LongTensor
Shape:  torch.Size([2, 3])
Value:  tensor([[ 3, 12, 21],
        [30, 39, 48]])


tensor([[ 3, 12, 21],
        [30, 39, 48]])

In [41]:
describe(torch.sum(x, dim=1))

Type:  torch.LongTensor
Shape:  torch.Size([2, 3])
Value:  tensor([[ 9, 12, 15],
        [36, 39, 42]])


tensor([[ 9, 12, 15],
        [36, 39, 42]])

In [43]:
describe(torch.sum(x, dim=2))

Type:  torch.LongTensor
Shape:  torch.Size([2, 3])
Value:  tensor([[ 3, 12, 21],
        [30, 39, 48]])


tensor([[ 3, 12, 21],
        [30, 39, 48]])

In [45]:
describe(torch.sum(x, dim=-2))

Type:  torch.LongTensor
Shape:  torch.Size([2, 3])
Value:  tensor([[ 9, 12, 15],
        [36, 39, 42]])


tensor([[ 9, 12, 15],
        [36, 39, 42]])

In [47]:
describe(torch.sum(x, dim=-3))

Type:  torch.LongTensor
Shape:  torch.Size([3, 3])
Value:  tensor([[ 9, 11, 13],
        [15, 17, 19],
        [21, 23, 25]])


tensor([[ 9, 11, 13],
        [15, 17, 19],
        [21, 23, 25]])

In [48]:
describe(torch.transpose(x,0,1))

Type:  torch.LongTensor
Shape:  torch.Size([3, 2, 3])
Value:  tensor([[[ 0,  1,  2],
         [ 9, 10, 11]],

        [[ 3,  4,  5],
         [12, 13, 14]],

        [[ 6,  7,  8],
         [15, 16, 17]]])


tensor([[[ 0,  1,  2],
         [ 9, 10, 11]],

        [[ 3,  4,  5],
         [12, 13, 14]],

        [[ 6,  7,  8],
         [15, 16, 17]]])

Indexing slicing and other functionalities.

In [65]:
x = torch.arange(6).view(2,3)

describe(x)

Type:  torch.LongTensor
Shape:  torch.Size([2, 3])
Value:  tensor([[0, 1, 2],
        [3, 4, 5]])


tensor([[0, 1, 2],
        [3, 4, 5]])

In [53]:
describe(x[:1, :2])

Type:  torch.LongTensor
Shape:  torch.Size([1, 2])
Value:  tensor([[0, 1]])


tensor([[0, 1]])

In [54]:
describe(x[0,1])

Type:  torch.LongTensor
Shape:  torch.Size([])
Value:  tensor(1)


tensor(1)

In [64]:
indices = torch.LongTensor([0,2])
indices_non_tensor = [0,2]

describe(x.index_select(dim=1, index=indices))

Type:  torch.LongTensor
Shape:  torch.Size([2, 2])
Value:  tensor([[0, 2],
        [3, 5]])


tensor([[0, 2],
        [3, 5]])

In [61]:
describe(torch.cat([x,x],dim=0))

Type:  torch.LongTensor
Shape:  torch.Size([4, 3])
Value:  tensor([[0, 1, 2],
        [3, 4, 5],
        [0, 1, 2],
        [3, 4, 5]])


tensor([[0, 1, 2],
        [3, 4, 5],
        [0, 1, 2],
        [3, 4, 5]])

In [72]:
describe(torch.mm(x,x.transpose(0,1)))

Type:  torch.LongTensor
Shape:  torch.Size([2, 2])
Value:  tensor([[ 5, 14],
        [14, 50]])


tensor([[ 5, 14],
        [14, 50]])