In [77]:
def describe(x):
    print("Type: ", x.type())
    print("Shape: ", x.shape)
    print("Value: ", x)
    return x

In [78]:
import torch

print(describe(torch.Tensor(2,3)))

Type:  torch.FloatTensor
Shape:  torch.Size([2, 3])
Value:  tensor([[0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 4.5914e-41]])
tensor([[0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 4.5914e-41]])


In [79]:
device = torch.device('cuda' if torch.cuda.is_available else 'gpu')

In [80]:
try:
    describe(device)
except:
    pass

In [81]:
describe(torch.rand(2, 3)) 
describe(torch.randn(2,3)) # normalised

Type:  torch.FloatTensor
Shape:  torch.Size([2, 3])
Value:  tensor([[0.6211, 0.2374, 0.2095],
        [0.4909, 0.2320, 0.3597]])
Type:  torch.FloatTensor
Shape:  torch.Size([2, 3])
Value:  tensor([[ 0.7392,  0.4670, -0.6319],
        [ 0.3447, -1.6481, -0.7665]])


tensor([[ 0.7392,  0.4670, -0.6319],
        [ 0.3447, -1.6481, -0.7665]])

In [82]:
describe(torch.zeros(2,3))

Type:  torch.FloatTensor
Shape:  torch.Size([2, 3])
Value:  tensor([[0., 0., 0.],
        [0., 0., 0.]])


tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [83]:
describe(torch.ones(2,3))

Type:  torch.FloatTensor
Shape:  torch.Size([2, 3])
Value:  tensor([[1., 1., 1.],
        [1., 1., 1.]])


tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [84]:
x = torch.ones(2,3)
describe(x)

describe(x.fill_(5))

Type:  torch.FloatTensor
Shape:  torch.Size([2, 3])
Value:  tensor([[1., 1., 1.],
        [1., 1., 1.]])
Type:  torch.FloatTensor
Shape:  torch.Size([2, 3])
Value:  tensor([[5., 5., 5.],
        [5., 5., 5.]])


tensor([[5., 5., 5.],
        [5., 5., 5.]])

In [85]:
x = torch.Tensor([[1,2,3], [4,5,6]])

describe(x)

Type:  torch.FloatTensor
Shape:  torch.Size([2, 3])
Value:  tensor([[1., 2., 3.],
        [4., 5., 6.]])


tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [86]:
import numpy as np

x = np.random.rand(2,3)

try:
    describe(x)
except:
    pass
x = np.random.randn(2,3)

try:
    describe(x)
except:
    pass

In [87]:
x = torch.from_numpy(x)

describe(x)

Type:  torch.DoubleTensor
Shape:  torch.Size([2, 3])
Value:  tensor([[ 1.5270, -1.5129, -0.0383],
        [ 0.8777,  0.0546,  1.1482]], dtype=torch.float64)


tensor([[ 1.5270, -1.5129, -0.0383],
        [ 0.8777,  0.0546,  1.1482]], dtype=torch.float64)

In [88]:
x = x.long()

describe(x)

Type:  torch.LongTensor
Shape:  torch.Size([2, 3])
Value:  tensor([[ 1, -1,  0],
        [ 0,  0,  1]])


tensor([[ 1, -1,  0],
        [ 0,  0,  1]])

In [89]:
x = torch.FloatTensor(torch.randn(2,3))

describe(x)

Type:  torch.FloatTensor
Shape:  torch.Size([2, 3])
Value:  tensor([[ 1.0639, -2.3886,  0.5745],
        [-0.6559,  0.2792,  0.3386]])


tensor([[ 1.0639, -2.3886,  0.5745],
        [-0.6559,  0.2792,  0.3386]])

Now lets look at some of the tensor operations.

In [90]:
torch.add(x,x)

describe(x)

Type:  torch.FloatTensor
Shape:  torch.Size([2, 3])
Value:  tensor([[ 1.0639, -2.3886,  0.5745],
        [-0.6559,  0.2792,  0.3386]])


tensor([[ 1.0639, -2.3886,  0.5745],
        [-0.6559,  0.2792,  0.3386]])

In [91]:
x = torch.arange(18)

describe(x)

x = x.view(2,3,3)

describe(x)

Type:  torch.LongTensor
Shape:  torch.Size([18])
Value:  tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17])
Type:  torch.LongTensor
Shape:  torch.Size([2, 3, 3])
Value:  tensor([[[ 0,  1,  2],
         [ 3,  4,  5],
         [ 6,  7,  8]],

        [[ 9, 10, 11],
         [12, 13, 14],
         [15, 16, 17]]])


tensor([[[ 0,  1,  2],
         [ 3,  4,  5],
         [ 6,  7,  8]],

        [[ 9, 10, 11],
         [12, 13, 14],
         [15, 16, 17]]])

In [92]:
describe(torch.sum(x, dim=0))

Type:  torch.LongTensor
Shape:  torch.Size([3, 3])
Value:  tensor([[ 9, 11, 13],
        [15, 17, 19],
        [21, 23, 25]])


tensor([[ 9, 11, 13],
        [15, 17, 19],
        [21, 23, 25]])

In [93]:
describe(torch.sum(x, dim=-1))

Type:  torch.LongTensor
Shape:  torch.Size([2, 3])
Value:  tensor([[ 3, 12, 21],
        [30, 39, 48]])


tensor([[ 3, 12, 21],
        [30, 39, 48]])

In [94]:
describe(torch.sum(x, dim=1))

Type:  torch.LongTensor
Shape:  torch.Size([2, 3])
Value:  tensor([[ 9, 12, 15],
        [36, 39, 42]])


tensor([[ 9, 12, 15],
        [36, 39, 42]])

In [95]:
describe(torch.sum(x, dim=2))

Type:  torch.LongTensor
Shape:  torch.Size([2, 3])
Value:  tensor([[ 3, 12, 21],
        [30, 39, 48]])


tensor([[ 3, 12, 21],
        [30, 39, 48]])

In [96]:
describe(torch.sum(x, dim=-2))

Type:  torch.LongTensor
Shape:  torch.Size([2, 3])
Value:  tensor([[ 9, 12, 15],
        [36, 39, 42]])


tensor([[ 9, 12, 15],
        [36, 39, 42]])

In [97]:
describe(torch.sum(x, dim=-3))

Type:  torch.LongTensor
Shape:  torch.Size([3, 3])
Value:  tensor([[ 9, 11, 13],
        [15, 17, 19],
        [21, 23, 25]])


tensor([[ 9, 11, 13],
        [15, 17, 19],
        [21, 23, 25]])

In [98]:
describe(torch.transpose(x,0,1))

Type:  torch.LongTensor
Shape:  torch.Size([3, 2, 3])
Value:  tensor([[[ 0,  1,  2],
         [ 9, 10, 11]],

        [[ 3,  4,  5],
         [12, 13, 14]],

        [[ 6,  7,  8],
         [15, 16, 17]]])


tensor([[[ 0,  1,  2],
         [ 9, 10, 11]],

        [[ 3,  4,  5],
         [12, 13, 14]],

        [[ 6,  7,  8],
         [15, 16, 17]]])

Indexing slicing and other functionalities.

In [99]:
x = torch.arange(6).view(2,3)

describe(x)

Type:  torch.LongTensor
Shape:  torch.Size([2, 3])
Value:  tensor([[0, 1, 2],
        [3, 4, 5]])


tensor([[0, 1, 2],
        [3, 4, 5]])

In [100]:
describe(x[:1, :2])

Type:  torch.LongTensor
Shape:  torch.Size([1, 2])
Value:  tensor([[0, 1]])


tensor([[0, 1]])

In [101]:
describe(x[0,1])

Type:  torch.LongTensor
Shape:  torch.Size([])
Value:  tensor(1)


tensor(1)

In [102]:
indices = torch.LongTensor([0,2])
indices_non_tensor = [0,2]

describe(x.index_select(dim=1, index=indices))

Type:  torch.LongTensor
Shape:  torch.Size([2, 2])
Value:  tensor([[0, 2],
        [3, 5]])


tensor([[0, 2],
        [3, 5]])

In [103]:
describe(torch.cat([x,x],dim=0))

Type:  torch.LongTensor
Shape:  torch.Size([4, 3])
Value:  tensor([[0, 1, 2],
        [3, 4, 5],
        [0, 1, 2],
        [3, 4, 5]])


tensor([[0, 1, 2],
        [3, 4, 5],
        [0, 1, 2],
        [3, 4, 5]])

In [104]:
describe(torch.mm(x,x.transpose(0,1)))

Type:  torch.LongTensor
Shape:  torch.Size([2, 2])
Value:  tensor([[ 5, 14],
        [14, 50]])


tensor([[ 5, 14],
        [14, 50]])

requires_grad functionality

When we create a tensor with requires_grad = True we are requiring Pytorch to manage bookkeeping information that computes gradients. Then at the end of computations, a single scalar is used to compute a backward pass.

The backward pass is initiated by using the backward() method on a tensor resulting from the
evaluation of a loss function. The backward pass computes a gradient value for a tensor object that
participated in the forward pass.

In [105]:
x = torch.ones(2,2,requires_grad=True)
describe(x)

Type:  torch.FloatTensor
Shape:  torch.Size([2, 2])
Value:  tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


tensor([[1., 1.],
        [1., 1.]], requires_grad=True)

In [106]:
print(x.grad is None)

True


In [107]:
y = (x+2) * (x+5) +3
describe(y)
print(x.grad)

Type:  torch.FloatTensor
Shape:  torch.Size([2, 2])
Value:  tensor([[21., 21.],
        [21., 21.]], grad_fn=<AddBackward0>)
None


In [108]:
try:
    y.backward()
    x.grad
except Exception as e:
    print(e)

grad can be implicitly created only for scalar outputs


In [109]:
z = y.mean()
describe(z)
z.backward()

y.grad, x.grad # y is the non leaf tensor accessed

Type:  torch.FloatTensor
Shape:  torch.Size([])
Value:  tensor(21., grad_fn=<MeanBackward0>)


<ipython-input-109-4236c0d2aa6b>:5: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the gradient for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more information.
  y.grad, x.grad # y is the non leaf tensor accessed


(None,
 tensor([[2.2500, 2.2500],
         [2.2500, 2.2500]]))

### Exercises

In [110]:
#1 

x = torch.randn(2,2)
describe(x)

Type:  torch.FloatTensor
Shape:  torch.Size([2, 2])
Value:  tensor([[ 0.1171, -0.4101],
        [-1.1601, -2.0141]])


tensor([[ 0.1171, -0.4101],
        [-1.1601, -2.0141]])

In [111]:
x.unsqueeze(0)

tensor([[[ 0.1171, -0.4101],
         [-1.1601, -2.0141]]])

In [112]:
#2

x.squeeze(0)

tensor([[ 0.1171, -0.4101],
        [-1.1601, -2.0141]])

In [113]:
#3
x = torch.rand(5,3)
describe(x)

Type:  torch.FloatTensor
Shape:  torch.Size([5, 3])
Value:  tensor([[0.6269, 0.0194, 0.8534],
        [0.7882, 0.6579, 0.1048],
        [0.2572, 0.5618, 0.9316],
        [0.6288, 0.6053, 0.3708],
        [0.1356, 0.2003, 0.5736]])


tensor([[0.6269, 0.0194, 0.8534],
        [0.7882, 0.6579, 0.1048],
        [0.2572, 0.5618, 0.9316],
        [0.6288, 0.6053, 0.3708],
        [0.1356, 0.2003, 0.5736]])

In [114]:
3 + x

tensor([[3.6269, 3.0194, 3.8534],
        [3.7882, 3.6579, 3.1048],
        [3.2572, 3.5618, 3.9316],
        [3.6288, 3.6053, 3.3708],
        [3.1356, 3.2003, 3.5736]])

In [115]:
3 + x * (7-3)

tensor([[5.5078, 3.0776, 6.4137],
        [6.1526, 5.6315, 3.4191],
        [4.0287, 5.2471, 6.7265],
        [5.5153, 5.4213, 4.4831],
        [3.5425, 3.8010, 5.2942]])

In [116]:
#4

x = torch.randn(2,2)
describe(x)

x.normal_()

Type:  torch.FloatTensor
Shape:  torch.Size([2, 2])
Value:  tensor([[ 0.5780, -0.6812],
        [ 0.8201,  0.2657]])


tensor([[-0.6136,  0.2862],
        [ 0.4747,  0.2210]])

In [117]:
a = torch.Tensor([1,1,1,0,1])

y = [x!=0 for x in a]
y

[tensor(True), tensor(True), tensor(True), tensor(False), tensor(True)]

In [118]:
for i in range(len(y)):
    if (y[i]==True):
        print(i)

0
1
2
4


In [119]:
torch.nonzero(a)

tensor([[0],
        [1],
        [2],
        [4]])

In [120]:
#6

x = torch.rand(3,1)
describe(x)
x.expand(3,4)

Type:  torch.FloatTensor
Shape:  torch.Size([3, 1])
Value:  tensor([[0.5471],
        [0.1677],
        [0.5827]])


tensor([[0.5471, 0.5471, 0.5471, 0.5471],
        [0.1677, 0.1677, 0.1677, 0.1677],
        [0.5827, 0.5827, 0.5827, 0.5827]])

In [121]:
#7

a = torch.rand(3,4,5)
b = torch.rand(3,5,4)

In [122]:
torch.bmm(a,b)

tensor([[[1.0485, 1.9395, 1.7866, 1.8221],
         [0.4185, 0.8353, 0.7905, 0.9803],
         [1.0286, 1.8795, 1.7339, 1.4548],
         [0.9295, 1.6154, 1.4097, 1.4657]],

        [[1.2085, 0.4274, 0.7451, 0.8226],
         [1.0946, 0.6938, 0.9085, 0.9036],
         [0.7303, 0.6341, 0.8205, 0.5076],
         [1.6149, 0.6392, 0.9074, 0.9273]],

        [[1.5482, 1.7966, 0.6073, 0.8295],
         [1.6087, 1.7916, 0.3827, 1.0784],
         [1.7385, 2.3849, 0.8807, 1.2061],
         [0.8166, 1.5187, 0.3449, 0.5478]]])

In [123]:
try:
    a*b
except:
    pass

In [124]:
#8

a = torch.rand(3,4,5)
b = torch.rand(5,4)

torch.bmm(a, b.unsqueeze(0).expand(a.size(0), *b.size()))

tensor([[[1.7233, 2.3406, 1.4742, 2.5645],
         [1.2071, 1.2486, 0.6893, 1.3125],
         [1.8799, 2.5713, 1.5047, 2.4538],
         [1.0478, 1.2316, 0.6970, 1.3562]],

        [[1.2163, 1.7533, 1.1250, 1.6813],
         [2.2966, 2.1826, 1.3385, 2.7077],
         [1.6110, 2.3529, 1.3342, 2.1600],
         [1.6843, 1.5703, 1.0627, 2.1625]],

        [[0.6027, 1.0543, 0.6337, 1.1010],
         [1.8433, 2.1209, 1.2628, 2.3658],
         [0.3552, 0.4023, 0.2194, 0.3853],
         [1.7824, 1.6512, 1.0508, 2.0512]]])

In [126]:
# new commands

#unsqueeze, expand, bmm 